routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Bpanel4\Clients\Http\Controllers\ClientAdminController;
use Bittacora\Bpanel4\Clients\Http\Controllers\LoginController;
use Bittacora\Bpanel4\Clients\Http\Controllers\MyAccountController;

Route::get('/iniciar-sesion', [LoginController::class, 'index'])->name('client-login')->middleware(['web']);

Route::prefix('mi-cuenta')->name('my-account.')->middleware(['web'])->group(function () {
    Route::get('/', [MyAccountController::class, 'index'])->name('index');
    Route::put('/actualizar', [MyAccountController::class, 'update'])->name('update');
    Route::get('/contrasena-actualizada', [MyAccountController::class, 'passwordUpdated'])->name('password-updated');

    // Direcciones
    Route::get('/{client}/direcciones', [MyAccountController::class, 'manageAddresses'])->name('manage-addresses');
    Route::get('/direcciones/{address}/editar', [MyAccountController::class, 'editAddress'])->name('edit-address');
    Route::get('/direcciones/crear', [MyAccountController::class, 'createAddress'])->name('create-address');
});

Route::prefix('bpanel/clientes')->name('bpanel4-clients.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(function () {
        Route::get('/', [ClientAdminController::class, 'index'])->name('index');
        Route::get('/{client}/editar', [ClientAdminController::class, 'edit'])->name('edit');
        Route::put('/{client}/actualizar', [ClientAdminController::class, 'update'])->name('update');
        Route::get('/{client}/direcciones', [ClientAdminController::class, 'addresses'])->name('addresses');
        Route::get('/direcciones/{address}/editar', [ClientAdminController::class, 'editAddress'])->name('edit-address');
        Route::delete('/{client}/eliminar', [ClientAdminController::class, 'destroy'])->name('destroy');
    });

resources/views/bpanel/addresses.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Edición de cliente: ' . $client->getFullName())

@section('content')

    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('user::form.edit') }}</span>
            </h4>
        </div>
        @include('bpanel4-addresses::public.manage-addresses', [
            'model' => $client,
            'editAddressRouteName' => 'bpanel4-clients.edit-address'
         ])
    </div>

@endsection

resources/views/bpanel/edit-address.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Edición de dirección: ' . $address->name)
@livewireStyles

@section('content')
    <div class="mb-3 tabs-level tabs-level-1  has-children ">
        <ul class="mt-10 mb-10 nav nav-justified flex-nowrap nav-tabs nav-tabs-simple nav-tabs-faded nav-tabs-detached radius-0 border-1 bgc-grey-l1 brc-grey-l1 pb-0 shadow-sm" role="tablist">
            <li class="nav-item mr-1px">
                <a class="btn bgc-white btn-lighter-grey btn-h-outline-blue btn-a-outline-blue py-2 btn-brc-tp border-none border-t-3 radius-0 letter-spacing active"
                   href="{{ route('bpanel4-clients.edit', ['client' => $address->addressable->id]) }}">
                    <i class="fa fa-pencil text-180 d-block my-1"></i>
                    <span class="text-90">Datos del cliente</span>
                </a>
            </li>
             <li class="nav-item mr-1px">
                <a class="btn bgc-white btn-lighter-grey btn-h-outline-blue btn-a-outline-blue py-2 btn-brc-tp border-none border-t-3 radius-0 letter-spacing active"
                   href="{{ route('bpanel4-clients.addresses', ['client' => $address->addressable]) }}">
                    <i class="fa fa-map-marker text-180 d-block my-1"></i>
                    <span class="text-90">Direcciones</span>
                </a>

            </li>
        </ul>
    </div>
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('user::form.edit') }}</span>
            </h4>
        </div>
        @include('bpanel4-addresses::bpanel.edit-address-form', ['model' => $address])
    </div>
@endsection
@livewireScripts

resources/views/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Edición de cliente: ' . $client->getFullName())

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('user::form.edit') }}</span>
            </h4>
        </div>
        @if($errors->any())
            <div class="alert alert-danger m-3">
                {!! implode('', $errors->all('<div>:message</div>')) !!}
            </div>
        @endif

        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-clients.update', $client)}}">
            @method('PUT')
            @csrf
            @livewire('form::input-text', ['name' => 'name', 'labelText' => __('bpanel4-clients::client.name'), 'required'=>true, 'value' => old('name') ?? $client->name ])
            @livewire('form::input-text', ['name' => 'surname', 'labelText' => __('bpanel4-clients::client.surname'), 'required'=>true, 'value' => old('surname') ?? $client->surname])
            @livewire('form::input-text', ['name' => 'dni', 'labelText' => __('bpanel4-clients::client.dni'), 'required'=>true, 'value' => old('dni') ?? $client->dni])
            @livewire('form::input-text', ['name' => 'company', 'labelText' => __('bpanel4-clients::client.company-name-label'), 'required'=>false, 'value' => old('company') ?? $client->company])
            @livewire('form::input-email', ['name' => 'email', 'labelText' => __('bpanel4-clients::client.email'), 'required'=>true, 'value' => old('email') ?? $client->user->email])
            @livewire('form::input-text', ['name' => 'phone', 'labelText' => __('bpanel4-clients::client.phone'), 'required'=>true, 'value' => old('phone') ?? $client->phone])
            <div class="form-group form-row">
                <div class="col-sm-3 col-form-label text-sm-right"></div>
                <div class="col-sm-7">
                    <strong>Dirección de envío predeterminada</strong>
                </div>
            </div>
            @include('bpanel4-addresses::bpanel.edit-address-fields', ['model' => $client->getShippingAddress()])
            <div class="form-group form-row">
                <div class="col-sm-3 col-form-label text-sm-right"></div>
                <div class="col-sm-7">
                    <hr/>
                </div>
            </div>
            @livewire('form::input-password', ['name' => 'password', 'labelText' => __('bpanel4-clients::client.password'), 'labelWidth' => 3, 'fieldWidth' => 7])
            @livewire('form::input-password', ['name' => 'password_confirmation', 'labelText' => __('bpanel4-clients::client.password_confirmation'), 'labelWidth' => 3, 'fieldWidth' => 7])
            <div class="form-group form-row">
                <div class="col-sm-3 col-form-label text-sm-right"></div>
                <div class="col-sm-7">
                    <em>Deje los campos de contraseña en blanco si no desea cambiar la contraseña del cliente.</em>
                </div>
            </div>

            @livewire('utils::created-updated-info', ['model' => $client])

            @livewire('form::input-checkbox', [
                'name' => 'active',
                'value' => 1,
                'labelText' => 'Activado',
                'bpanelForm' => true,
                'checked' => $client->getUser()->getActive() == 1
            ])
            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'update'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
            @livewire('form::input-hidden', ['name' => 'client_id', 'value' => $client->id])
        </form>
    </div>

@endsection

resources/views/bpanel/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Clientes')

@section('content')

    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-clients::datatable.index') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('bpanel4-clients::livewire.clients-table', [], key('bpanel4-clients-datatable'))
        </div>
    </div>


@endsection

resources/views/bpanel/livewire/client-datatable.blade.php
{{--<td>
    <div class="text-center">
        {{$row->name}}
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->surname}}
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->user->email}}
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->company}}
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->dni}}
    </div>
</td>
<td>
    <div class="text-center">
        {{ $row->mainAddress?->country->name }}
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->mainAddress?->state->name}}
    </div>
</td>
<td>
    <div class="text-center">
        {{$row->mainAddress?->location}}
    </div>
</td>
<td>
    <div class="text-center">
        {{ $row->getClientTypeName() }}
    </div>
</td>
<td>
    <div class="text-center">
        {{\Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $row->created_at)->format('d/m/Y H:i')}}
    </div>
</td>
<td>
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row->user, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))
</td>
<td>
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-clients', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el cliente?'], key('user-buttons-'.$row->id))
    </div>
</td>
--}}

resources/views/bpanel/livewire/datatable-columns/actions.blade.php
@livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-clients', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el cliente?'], key('user-buttons-'.$row->id))

resources/views/bpanel/livewire/datatable-columns/active.blade.php
@if(null !== $row->user)
    @livewire('utils::datatable-default', [
        'fieldName' => 'active',
        'model' => $row->user,
        'value' => $row->user->active,
        'size' => 'xxs'
    ], key('active-user-'.$row->id))
@endif